BEGIN TRANSACTION;
CREATE TABLE `Campus_Locations` (
	`Node ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Latitude`	REAL NOT NULL UNIQUE,
	`Longitude`	REAL NOT NULL UNIQUE,
	`Description`	TEXT,
	`Image`	BLOB
);
INSERT INTO `Campus_Locations` VALUES (1,'EEC',52.405341,-1.500019,'This building was completed in 2012 and is used solely by our Faculty of Engineering, Environment and Computing. The £55m project delivered a highly sustainable building that uses a range of technologies including rainwater harvesting, solar thermal energy and biomass boilers. Facilities include a high precision wind-tunnel, a £3m high-performance engineering centre, a Harrier Jump Jet, three flight simulators and the UK’s largest magnet.',NULL);
INSERT INTO `Campus_Locations` VALUES (2,'Alan Berry',52.408037,-1.59573,'This was constructed in 1963 and has a prominent position on our campus overlooking University Square.  This building is used by our Business Development, Registry and the Vice Chancellors Office. This was named after Alan Berry who was the Director and Chief Executive for the West Midlands Engineering Employers’ Association.',NULL);
INSERT INTO `Campus_Locations` VALUES (3,'Alma ',52.410006,-1.50044,'This was built in the 1920’s and is the home of our professional services such as Estates, HR and Finance. This was the site of the Singer Works, out of which the Singer Penny Farthing was born and it also holds the origins to Coventry City Football Club.',NULL);
INSERT INTO `Campus_Locations` VALUES (4,'Armstrong Siddeley',52.407539,-1.500747,'This is the location of CU Coventry which opened in 2012, offering a new concept in HE, designed to integrate study into your life. The building was built in the 1970’s and is named after the Coventry based engineering group  that operated during the first half of the 20th Century. They were renowned for the design and build of cars, aero-engines and aircraft and were absorbed into Rolls-Royce in 1966.',NULL);
INSERT INTO `Campus_Locations` VALUES (5,'Bugatti',52.407517,-1.503339,'This building funded by the Bugatti trust was built in 2002 and provides a valuable space for our Faculty of Arts and Humanities. In particular this is used in the areas of Automotive & Transport Design with very strong industry links.',NULL);
INSERT INTO `Campus_Locations` VALUES (6,'Charles Ward',52.408539,-1.505215,'Built in the 1950’s this building is used mainly by our Faculty of Health and Life Sciences. The building was named after a key figure for the University, who was a University Governor, and became Vice Chair of the Board of Governors in 1982.',NULL);
INSERT INTO `Campus_Locations` VALUES (7,'Ellen Terry',52.406675,-1.504673,'This building is used by our Faculty of Arts and Humanities, specifically for the Performing Arts, Media and Music Students. Fittingly this building previously was a cinema, originally built in 1880 with a major refurbishment in 2000. The building has been named after Dame Ellen Terry, a star of the Victoria stage and a leading Shakespearean actress.',NULL);
INSERT INTO `Campus_Locations` VALUES (8,'Frederick Lanchester Library',52.405949,-1.500649,'This modern and striking building houses the main University library, and was completed in 2001. It has been named after the Coventry based designer of the first British petrol-driven car. With a number of different study zones across 5 floors, it provides an invaluable central study and resource space for staff and students. It is equipped with over 350 computers, group and individual study rooms, books, journals, and electronic resources.',NULL);
INSERT INTO `Campus_Locations` VALUES (9,'George Eliot',52.408021,-1.504857,'This building was built in 1960 and is used solely by our Faculty of Business and Law. George Eliot is the pen name of the novelist Mary Anne Evans (1819-1880) and was one of the leading writers of the Victorian era.',NULL);
INSERT INTO `Campus_Locations` VALUES (10,'Graham Sutherland',52.407039,-1.503123,'Built in 1959, this building is used by our Faculty of Arts and Humanities, predominately for the Design and Visual Art students, fitted with a full commercial fashion studio. This building was aptly named after the painter and print maker who created the world famous tapestry Christ in Glory hanging in Coventry Cathedral.',NULL);
INSERT INTO `Campus_Locations` VALUES (11,'TheHUB',52.40742,-1.504781,'Completed in 2011 TheHub is a modern, hi-tech building providing a welcoming social space for our students. Facilities in the building include a doctors’ surgery, a multi-cultural faith centre, employment services, catering services, as well as hairdressers, food court and the Students’ Union offices. This building also has a large fully licensed function space with bars and a multi-purpose venue space. The building achieved a BREEAM status of Excellent.',NULL);
INSERT INTO `Campus_Locations` VALUES (12,'Jaguar',52.407141,-1.500483,'This building was built in the late 1970’s and sponsored by the Coventry based car manufacturer. It has recently undergone a significant refurbishment, with additional improvements planned.  It is now home to our Postgraduate students, as well as our researchers within the Centre for Business in Society (CBiS). ',NULL);
INSERT INTO `Campus_Locations` VALUES (13,'James Starley',52.407671,-1.504091,'Built in the late 1950’s, this is home to our Faculty of Health and Life Sciences. It was named after the British inventor of the Coventry tricycle and father of the bicycle industry.',NULL);
INSERT INTO `Campus_Locations` VALUES (14,'Maurice Foss',52.407763,-1.503017,'Built in 1978, this building is used by our Faculty of Arts and Humanities, who mainly run their Industrial Design courses from here. The building has been named after the former Deputy Director of Coventry Polytechnic and one of the University’s Honorary Life Fellows.',NULL);
INSERT INTO `Campus_Locations` VALUES (15,'Multi Storey Car Park',52.406256,-1.499583,'This is our impressive Multi-storey car park, opened for staff and visitors in 2010. It has 457 spaces over 15 floors, including spaces for electric vehicles.',NULL);
INSERT INTO `Campus_Locations` VALUES (16,'Priory',52.40925,-1.505901,'Built in 1964, this building is occupied by the Cambridge Education Group, who run their Foundation Campus from here. They offer University Pathway courses for foreign students who wish to gain entry to UK Universities. Also in this building is a large sports hall, and the University’s Student Union Radio.',NULL);
INSERT INTO `Campus_Locations` VALUES (17,'Richard Crossman',52.406607,-1.505149,'This was built in 1971 and has been named after the political journalist and Labour politician, representing Coventry East from 1945-1974. This is the main building for the Faculty of Health and Life Sciences and includes a mock hospital ward and operating theatre, complete with sink scrubs and theatre lights.',NULL);
INSERT INTO `Campus_Locations` VALUES (18,'Sir John Laing',52.405821,-1.504992,'This building was built in 1970, and was named after the knighted British entrepreneur in the construction industry. This building is primarily used by the Faculty of Engineering, Environment and Computing, offering courses relating to the construction industry.',NULL);
INSERT INTO `Campus_Locations` VALUES (19,'Sir William Lyons',52.407337,-1.499745,'Constructed in1980, this building is home to our IT services. Sir William Lyons was the co-founder of the Swallow Sidecar Company which subsequently became Jaguar Cars Limited.',NULL);
INSERT INTO `Campus_Locations` VALUES (20,'Student Centre',52.404937,-1.500778,'Construction was completed in 2006, and as its name suggests is home to some key student services as well as our International Office. This is where our students enroll as well as the main information point for student accommodation and finance queries.',NULL);
INSERT INTO `Campus_Locations` VALUES (21,'Whitefriars',52.405105,-1.50161,'This is a small office used by our Faculty of Health and Life Sciences. Built in 1922 and its name is drawn from the Carmelite Friary founded in 1342 in Coventry.',NULL);
INSERT INTO `Campus_Locations` VALUES (22,'William Morris',52.406546,-1.501188,'This building began life in 1910 as a factory and has been named after the founder of the Morris car company who used this building as part of its engine production unit. It was converted for use by the University and is now occupied by our Faculty of Business and Law. ',NULL);
INSERT INTO `Campus_Locations` VALUES (23,'Sports and Recreation Centre',52.405702,-1.504187,'Our own Sports and Recreation Centre offers a wide range of activities for all sporting tastes, available for use by Staff and Students. Most of the University accommodation includes free membership to the Centre.',NULL);
COMMIT;
